### ISSUE TITLE
Error when analyzing tif

### ISSUE THREAD

**Issue by Monodia97** [PerezOrtegaJ/Xsembles2P#1]
Hello,
Happy to use Xsembles2P, but there are some errors and I don't know how to solve
![error sreenshot](https://github.com/PerezOrtegaJ/Xsembles2P/assets/80382483/a9bcd969-6ea5-4365-a51d-ffce44902c63)

**Comment by PerezOrtegaJ** [comment]
Hi,
Thanks for bringing this up. For a quick fix, it is necessary to change 'ori' to 'none' in line 24 of the Plot_Xsemble_Raster.m file. The corrected line should look like this:
```matlab
[vector_id_sorted,neuron_id_sorted,ensemble_id] = Vector_and_Neuron_ID(data,'none');
```

**Comment by PerezOrtegaJ** [comment]
The file is updated now!
