### ISSUE TITLE
Error when clicking on the neuron ROI

### ISSUE THREAD

**Issue by Monodia97** [PerezOrtegaJ/Xsembles2P#2]
Sorry but I met another question. I click Plot Spatial location and then click on the neuron ROI. It showed these errors. How can I solve it? Thank you.

![xsembles error](https://github.com/PerezOrtegaJ/Xsembles2P/assets/80382483/40388a4c-69c1-40b3-84e3-4b9570a60850)
![xsembles——error](https://github.com/PerezOrtegaJ/Xsembles2P/assets/80382483/f1f46cef-1fb5-4939-b302-b7921a02695e)

**Comment by PerezOrtegaJ** [comment]
Hi. No problem. I forgot to change the name of the field of the structure variable. It needs to be `Activity` instead of `ActivityBinary` in line 53 of the Plot_Neuron_Signal.m file. The corrected line should look like this:
```matlab
ensemble_activity = data.Analysis.Ensembles.Activity;
```

**Comment by PerezOrtegaJ** [comment]
I have fixed the file!
